adda:
  gazebo_ros_control:
    pid_gains:
      # Traction Controller
      front_left_axle:
        p: 1500.0
        i: 10.0
        d: 0.0

      front_right_axle:
        p: 1500.0
        i: 10.0
        d: 0.0

      rear_left_axle:
        p: 1500.0
        i: 10.0
        d: 0.0

      rear_right_axle:
        p: 1500.0
        i: 10.0
        d: 0.0

# Steering Controller
  left_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}

  right_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}

# Traction Controller
  front_left_axle_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_axle

  front_right_axle_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_right_axle


  rear_left_axle_controller:
    type: velocity_controllers/JointVelocityController
    joint: rear_left_axle

  rear_right_axle_controller:
    type: velocity_controllers/JointVelocityController
    joint: rear_right_axle

# Joint Publisher Controller
  joint_read_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100.0